# Generated by Django 5.1.6 on 2025-08-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
