# Generated by Django 5.1.6 on 2025-07-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementimage',
            options={'ordering': ['order'], 'verbose_name': 'Объявление доп. изображене', 'verbose_name_plural': 'Объявления доп. изображения'},
        ),
    ]
