# Generated by Django 5.1.6 on 2025-06-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование службы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('icon_name', models.CharField(default='fa-info', max_length=64, verbose_name='Иконка (FontAwesome)')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Социальная служба',
                'verbose_name_plural': 'Социальные службы',
            },
        ),
        migrations.CreateModel(
            name='SocialPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='info.social')),
            ],
            options={
                'verbose_name': 'Телефон соцслужбы',
                'verbose_name_plural': 'Телефоны соцслужб',
            },
        ),
    ]
